package;

class Intro extends DoctorDialog {
	public function new() {
		super([
			"P SO HOW BAD IS IT DOCTOR?", "D WELL. I WON'T LIE TO YOU", "D YOU'RE GONNA DIE", "P OH...", "D SOON", "D VERY SOON", "D AND IT'LL BE PAINFUL",
			'D VERY VERY VERY PAINFUL', 'D EXTREMELY PAINFUL', 'P OH...', 'P IS THERE ANYTHING I CAN DO?', 'D I DON\'T THINK SO', 'D BUT ACTUALLY...',
			'D LIFE STOCK EXCHANGE APP', 'D HAVE YOU HEARD ABOUT IT?', 'P HUH?', 'P NO', "D THAT'S AN AWESOME APP!", "D YOU CAN SELL YOUR LIFE FOR BUCKS!",
			"P WOW!", "D AND YOU CAN BUY SOME!", "D GIVE IT A TRY!", "P BUT I ONLY GOT $100 ON ME", "D THAT'S A SHAME",
			"D MAYBE YOU CAN TRADE UP SOME IN THE APP", "D BY THE WAY", "D INSURENCE WON'T COVER THE TREATMENT", "P WHAT?!", "D SO YOU OWE US $10,000",
			"P OH MY...", "D YOU REALLY SHOULD TRY THE APP", "P PROBABLY I SHOULD JUST DIE", "D DON'T SAY THAT!", "D WE NEED YOUR MONEY AFTER ALL", "P ...",
			"D WELL...", "D GOOD LUCK!"
		], function() {
			machine.setState(new Trading());
		});
	}
}
